language: python

addons:
  sonarcloud:
    organization: "ler0i"
    token: 4Paf14hA6BMMiILzWXWsdg

install: "pip install -r requirements.txt"

script:
  - coverage run -a --source=src tests/testlab4.py  
  - sonar-scanner  
  after_success:  
- coveralls  
